/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-08-24 01:49:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.*;

public final class admin_005fpdt_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("utf-8");
int cpage = Integer.parseInt(request.getParameter("cpage"));
int psize = Integer.parseInt(request.getParameter("psize"));

// 검색조건 및 정렬조건 쿼리스트링을 받음
String id, isview, schtype, keyword, sdate, edate, bcata, scata, sprice, eprice, stock, ord;
id		= request.getParameter("id");		isview	= request.getParameter("isview");
schtype = request.getParameter("schtype");	keyword = request.getParameter("keyword");
sdate	= request.getParameter("sdate");	edate	= request.getParameter("edate");
bcata	= request.getParameter("bcata");	scata	= request.getParameter("scata");
sprice	= request.getParameter("sprice");	eprice	= request.getParameter("eprice");
stock	= request.getParameter("stock");	ord 	= request.getParameter("ord");

String args = "?cpage=" + cpage + "&psize=" + psize;
if (isview != null && !isview.equals(""))	args += "&isview=" + isview;
if (sdate != null && !sdate.equals(""))		args += "&sdate=" + sdate;
if (edate != null && !edate.equals(""))		args += "&edate=" + edate;
if (bcata != null && !bcata.equals(""))		args += "&bcata=" + bcata;
if (scata != null && !scata.equals(""))		args += "&scata=" + scata;
if (sprice != null && !sprice.equals(""))	args += "&sprice=" + sprice;
if (eprice != null && !eprice.equals(""))	args += "&eprice=" + eprice;
if (stock != null && !stock.equals(""))		args += "&stock=" + stock;
if (keyword != null && !keyword.equals(""))
	args += "&schtype=" + schtype + "&keyword=" + keyword;
if (ord != null && !ord.equals(""))			args += "&ord=" + ord;

PdtInfo pdtInfo = (PdtInfo)request.getAttribute("pdtInfo");

String plstock = String.valueOf(pdtInfo.getPl_stock());
if (plstock.equals("-1"))	plstock = "무제한";

float rate = (float)pdtInfo.getPl_discount() / 100;
int dcPrice = Math.round(pdtInfo.getPl_price() - (pdtInfo.getPl_price() * rate));

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("#thImg img { margin:10px; }\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("function showImg(imgName) {\r\n");
      out.write("\tvar bigImg = document.getElementById(\"bigImg\");\r\n");
      out.write("\tbigImg.src = \"/hoyaMall/product/pdt_img/\" + imgName;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2>상품 상세보기 화면</h2>\r\n");
      out.write("<table width=\"800\" cellpadding=\"5\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td width=\"40%\" align=\"center\" valign=\"middle\">\r\n");
      out.write("\t<table width=\"100%\">\r\n");
      out.write("\t<tr><td align=\"center\" valign=\"middle\">\r\n");
      out.write("\t\t<img src=\"/hoyaMall/product/pdt_img/");
      out.print(pdtInfo.getPl_img1() );
      out.write("\" width=\"300\" id=\"bigImg\" />\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t<tr><td align=\"center\" valign=\"middle\" id=\"thImg\">\r\n");
      out.write("\t\t<img src=\"/hoyaMall/product/pdt_img/");
      out.print(pdtInfo.getPl_img1() );
      out.write("\" width=\"80\" onclick=\"showImg('");
      out.print(pdtInfo.getPl_img1() );
      out.write("');\" />\r\n");
 if (pdtInfo.getPl_img2() != null && !pdtInfo.getPl_img2().equals("")) { 
      out.write("\r\n");
      out.write("\t\t<img src=\"/hoyaMall/product/pdt_img/");
      out.print(pdtInfo.getPl_img2() );
      out.write("\" width=\"80\" onclick=\"showImg('");
      out.print(pdtInfo.getPl_img2() );
      out.write("');\" />");
 } 
      out.write('\r');
      out.write('\n');
 if (pdtInfo.getPl_img3() != null && !pdtInfo.getPl_img3().equals("")) { 
      out.write("\r\n");
      out.write("\t\t<img src=\"/hoyaMall/product/pdt_img/");
      out.print(pdtInfo.getPl_img3() );
      out.write("\" width=\"80\" onclick=\"showImg('");
      out.print(pdtInfo.getPl_img3() );
      out.write("');\" />");
 } 
      out.write("\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</td>\r\n");
      out.write("<td width=\"*\"><!-- 상품명, 옵션, 가격, 재고량, 할인율, 등록일, 원가, 판매량, 관리자 번호 -->\r\n");
      out.write("\t<table width=\"100%\" cellpadding=\"8\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td width=\"100\">분류</td>\r\n");
      out.write("\t<td width=\"*\">");
      out.print(pdtInfo.getCb_name() + " - " + pdtInfo.getCs_name() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td>상품명</td><td>");
      out.print(pdtInfo.getPl_name() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr><td>원산지</td><td>");
      out.print(pdtInfo.getPl_orig() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr><td>가격</td><td>");
      out.print(pdtInfo.getPl_price() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr><td>원가</td><td>");
      out.print(pdtInfo.getPl_cost() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr><td>할인율</td><td>");
      out.print(pdtInfo.getPl_discount() );
      out.write("% (할인가격 : ");
      out.print(dcPrice );
      out.write(")</td></tr>\r\n");
      out.write("\t<tr><td>재고량</td><td>");
      out.print(plstock );
      out.write("</td></tr>\r\n");
      out.write("\t<tr><td>판매량</td><td>");
      out.print(pdtInfo.getPl_salecnt() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr><td>등록일</td><td>");
      out.print(pdtInfo.getPl_date() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr><td>등록자</td><td>");
      out.print(pdtInfo.getAl_idx() );
      out.write("</td></tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td colspan=\"2\" align=\"center\"><hr width=\"100%\" /></td></tr>\r\n");
      out.write("<tr><td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t<img src=\"/hoyaMall/product/pdt_img/");
      out.print(pdtInfo.getPl_desc() );
      out.write("\" width=\"780\" />\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td colspan=\"2\" align=\"center\"><hr width=\"100%\" /></td></tr>\r\n");
      out.write("<tr><td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t<input type=\"button\" value=\"목록\" onclick=\"location.href='admin_product_list.apdt");
      out.print(args );
      out.write("';\" />\r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t<input type=\"button\" value=\"수정\" onclick=\"location.href='admin_product_up_form.apdt");
      out.print(args );
      out.write("&id=");
      out.print(id );
      out.write("';\" />\r\n");
 if (pdtInfo.getPl_salecnt() == 0) {	// 판매된 적이 없을 경우에만 삭제 가능 
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function notCool(id) {\r\n");
      out.write("\tif (confirm(\"정말 삭제하시겠습니까?\\n삭제하면 복구가 불가능 합니다.\")) {\r\n");
      out.write("\t\tlocation.href=\"pdt_del_proc.pdta?id=\" + id;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t<input type=\"button\" value=\"삭제\" onclick=\"notCool('");
      out.print(id );
      out.write("');\" />\r\n");
 } 
      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br /><br />\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
