/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-08-18 05:52:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import vo.*;

public final class admin_005fpdt_005fin_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("utf-8");

ArrayList<CataBigInfo> cataBigList = (ArrayList<CataBigInfo>)request.getAttribute("cataBigList");
ArrayList<CataSmallInfo> cataSmallList = (ArrayList<CataSmallInfo>)request.getAttribute("cataSmallList");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script>\r\n");

String scName = null;
int bc = 0, sc = 0;
// bc : 대분류 idx를 저장하기 위한 변수로 배열의 이름으로 사용됨
// sc : 소분류 idx를 저장하기 위한 변수
for (int i = 0, j = 1 ; i < cataSmallList.size() ; i++, j++) {
// i : cataSmallList 에 들어있는 데이터의 개수만큼 루프를 돌리며 cataSmallList의 인덱스로 사용하기 위한 변수
// j : cataSmallList 의 값을 배열에 넣을 때 사용하기 위한 인덱스번호를 저장하는 변수
	if (bc != cataSmallList.get(i).getCb_idx()) {
	// 기존 대분류 idx(bc)와 현재 대분류 idx가 다르면-배열을 새롭게 생성
		j = 1;	// 새롭게 생성할 배열에 값을 넣을 때 사용할 인덱스 번호 초기화

      out.write("\r\n");
      out.write("var arr");
      out.print(cataSmallList.get(i).getCb_idx());
      out.write(" = new Array();\r\n");
      out.write("// 대분류 idx를 이용하여 유니크한 이름의 배열을 생성\r\n");
      out.write("arr");
      out.print(cataSmallList.get(i).getCb_idx());
      out.write("[0] = new Option(\"\", \"소분류 선택\");\r\n");
      out.write("// 배열의 0번 인덱스에 콤보박스의 제일 위에서 보여줄 option 아이템을 지정\r\n");

	}
	bc = cataSmallList.get(i).getCb_idx();	// 대분류 idx를 bc에 저장
	sc = cataSmallList.get(i).getCs_idx();	// 소분류 idx를 sc에 저장
	scName = cataSmallList.get(i).getCs_name();	// 대분류명을 scName에 저장

      out.write("\r\n");
      out.write("arr");
      out.print(bc);
      out.write('[');
      out.print(j);
      out.write("] = new Option(\"");
      out.print(sc);
      out.write("\", \"");
      out.print(scName);
      out.write("\");\r\n");
      out.write("// 소분류 콤보박스용 배열에 콤보박스에서 사용할 option태그를 생성하여 저장\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("function setCategory(obj, target) {\r\n");
      out.write("\tvar x = obj.value;\t// 대분류에서 선택한 값을 x에 담음\r\n");
      out.write("\r\n");
      out.write("\t// 소분류 콤보박스를 첫번째 option을 제외하고 모두 지움\r\n");
      out.write("\tfor (var m = target.options.length - 1 ; m > 0 ; m--) {\r\n");
      out.write("\t// target : sCata라는 소분류 콤보박스\r\n");
      out.write("\t// options : option이라는 태그들의 배열(여기서는 sCata라는 소분류 콤보박스의 option태그들 배열)\r\n");
      out.write("\t// length : 배열의 길이를 의미(여기서는 target의 options 배열의 길이를 뜻함)\r\n");
      out.write("\t// target.options.length - 1 : target이라는 컨트롤의 option태그 배열 개수에서 1을 뺌(즉, 마지막 인덱스 번호)\r\n");
      out.write("\t\ttarget.options[m] = null;\r\n");
      out.write("\t\t// target컨트롤의 options배열에 m번 인덱스에 해당하는 값(option태그)을 지움\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tif (x != \"\") {\r\n");
      out.write("\t// 대분류에서 특정 대분류를 선택했을 경우\r\n");
      out.write("\t\tvar selectedArray = eval(\"arr\" + x);\t// 보여줄 배열 지정\r\n");
      out.write("\t\t// 선택한 대분류에 속한 소분류들이 들어있는 배열을 selectedArray에 담음\r\n");
      out.write("\r\n");
      out.write("\t\tfor (var i = 0 ; i < selectedArray.length ; i++) {\r\n");
      out.write("\t\t\ttarget.options[i] = new Option(selectedArray[i].value, selectedArray[i].text);\r\n");
      out.write("\t\t\t// 소분류 콤보박스에 새로운 option태그를 지정함(selectedArray배열에서 value와 text를 가져옴)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ttarget.options[0].selected = true;\r\n");
      out.write("\t\t// 새롭게 만들어진 콤보박스에서 첫번째 option이 선택된 상태로 있게 함\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2>상품 등록 폼</h2>\r\n");
      out.write("<form name=\"frmPdt\" action=\"admin_product_in_proc.apdt\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("<table width=\"800\" cellpadding=\"5\" id=\"pdtInForm\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th width=\"150\">대분류</th>\r\n");
      out.write("<td width=\"250\">\r\n");
      out.write("\t<select name=\"bCata\" onchange=\"setCategory(this, this.form.sCata);\">\r\n");
      out.write("\t\t<option value=\"\">대분류 선택</option>\r\n");
 for (int i = 0 ; i < cataBigList.size() ; i++) { 
      out.write("\r\n");
      out.write("\t\t<option value=\"");
      out.print(cataBigList.get(i).getCb_idx());
      out.write('"');
      out.write('>');
      out.print(cataBigList.get(i).getCb_name());
      out.write("</option>\r\n");
 } 
      out.write("\r\n");
      out.write("\t</select>\r\n");
      out.write("</td>\r\n");
      out.write("<th width=\"150\">소분류</th>\r\n");
      out.write("<td width=\"250\">\r\n");
      out.write("\t<select name=\"sCata\">\r\n");
      out.write("\t\t<option value=\"\">소분류 선택</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>원산지</th><td><input type=\"text\" name=\"orig\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>상품명</th><td><input type=\"text\" name=\"name\" /></td>\r\n");
      out.write("<th>가격</th><td><input type=\"text\" name=\"price\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>원가</th><td><input type=\"text\" name=\"cost\" /></td>\r\n");
      out.write("<th>할인율</th><td><input type=\"text\" name=\"discount\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>이미지1</th><td><input type=\"file\" name=\"img1\" /></td>\r\n");
      out.write("<th>이미지2</th><td><input type=\"file\" name=\"img2\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>이미지3</th><td><input type=\"file\" name=\"img3\" /></td>\r\n");
      out.write("<th>설명이미지</th><td><input type=\"file\" name=\"desc\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>재고</th>\r\n");
      out.write("<td>\r\n");
      out.write("\t<select name=\"stock\">\r\n");
      out.write("\t\t<option value=\"-1\">무제한</option>\r\n");
 for (int i = 0 ; i <= 100 ; i++) { 
      out.write("\r\n");
      out.write("\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");
 } 
      out.write("\r\n");
      out.write("\t</select> EA\r\n");
      out.write("</td>\r\n");
      out.write("<th>게시여부</th>\r\n");
      out.write("<td>\r\n");
      out.write("\t<input type=\"radio\" name=\"view\" value=\"y\" />상품 게시\r\n");
      out.write("\t<input type=\"radio\" name=\"view\" value=\"n\" checked=\"checked\" />상품 미게시\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t<input type=\"submit\" value=\"상품 등록\" />\r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t<input type=\"reset\" value=\"다시 입력\" />\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
