/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-09-23 00:57:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import vo.*;

public final class pdt_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

ArrayList<PdtInfo> pdtList = (ArrayList<PdtInfo>)request.getAttribute("pdtList");
ArrayList<PdtInfo> pdtPotList = (ArrayList<PdtInfo>)request.getAttribute("pdtPotList");
ArrayList<CataBigInfo> cataBigList = (ArrayList<CataBigInfo>)request.getAttribute("cataBigList");
ArrayList<CataSmallInfo> cataSmallList = (ArrayList<CataSmallInfo>)request.getAttribute("cataSmallList");
PdtPageInfo pageInfo = (PdtPageInfo)request.getAttribute("pageInfo");
MemberInfo loginMember = (MemberInfo)session.getAttribute("loginMember");

String keyword, bcata, scata, sprice, eprice, ord;
keyword =	pageInfo.getKeyword();	// 검색어
bcata =		pageInfo.getBcata();	// 대분류
scata =		pageInfo.getScata();	// 소분류
sprice =	pageInfo.getSprice();	// 가격대 시작 가격
eprice =	pageInfo.getEprice();	// 가격대 종료 가격
ord =		pageInfo.getOrd();		// 정렬조건

String args = "", schArgs = "";
if (bcata != null)		schArgs += "&bcata=" + bcata;		else	bcata = "";
if (scata != null)		schArgs += "&scata=" + scata;		else	scata = "";
if (sprice != null)		schArgs += "&sprice=" + sprice;		else	sprice = "";
if (eprice != null)		schArgs += "&eprice=" + eprice;		else	eprice = "";
if (keyword != null)	schArgs += "&keyword=" + keyword;	else	keyword = "";
if (ord != null)		schArgs += "&ord=" + ord;			else	ord = "";

int cpage	= pageInfo.getCpage();	// 현재 페이지 번호
int pcnt	= pageInfo.getPcnt();	// 전체 페이지 수
int psize	= pageInfo.getPsize();	// 페이지 크기
int bsize	= pageInfo.getBsize();	// 블록 페이지 개수
int spage	= pageInfo.getSpage();	// 블록 시작 페이지 번호
int epage	= pageInfo.getEpage();	// 블록 종료 페이지 번호
int rcnt	= pageInfo.getRcnt();	// 검색된 게시물 개수
schArgs = "&psize=" + psize + schArgs;
args = "&cpage=" + cpage + schArgs;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\"\r\n");
      out.write("    />\r\n");
      out.write("<style>\r\n");
      out.write("td { font-size:11; }\r\n");
      out.write(".pr { width:50px; }\r\n");
      out.write(".pdtBox3 { width:266px; height:265px;  }\r\n");
      out.write(".pdtBox4 { width:195px; height:215px; }\r\n");
      out.write(".bestContainer { width: 100%; height:auto;}\r\n");
      out.write(".bestWrap { \r\n");
      out.write("margin: 0 auto;\r\n");
      out.write("width: 1200px; \r\n");
      out.write("height: auto; \r\n");
      out.write("display: flex;\r\n");
      out.write("flex-direction: row;\r\n");
      out.write("flex-wrap: no-wrap;\r\n");
      out.write("justify-content: flex-start;\r\n");
      out.write("align-items: center;\r\n");
      out.write(" }\r\n");
      out.write(".bestItem { \r\n");
      out.write("width: 400px;\r\n");
      out.write("height: 500px;  \r\n");
      out.write("  }\r\n");
      out.write(".fntCenter{\r\n");
      out.write("text-align: center;\r\n");
      out.write("}\r\n");
      out.write("  * {\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("      }\r\n");
      out.write("      body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        background-color: #fcfafa;\r\n");
      out.write("      }\r\n");
      out.write("      a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("      }\r\n");
      out.write("      a:visited {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("      }\r\n");
      out.write("      a:hover {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("      }\r\n");
      out.write("      a:focus {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("      }\r\n");
      out.write("      a:hover,\r\n");
      out.write("      a:active {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("      }\r\n");
      out.write("      input:focus {\r\n");
      out.write("        outline: none;\r\n");
      out.write("      }\r\n");
      out.write("      .container {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        background-color: #fcfafa;\r\n");
      out.write("      }\r\n");
      out.write("      .header {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("      }\r\n");
      out.write("      .logoBox {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        flex-wrap: nowrap;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        width: 410px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("      }\r\n");
      out.write("      .box {\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      .left {\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("      }\r\n");
      out.write("      .right {\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        text-align: right;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("      }\r\n");
      out.write("      .line {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("      }\r\n");
      out.write("      .lineItem {\r\n");
      out.write("        border: 1px solid black;\r\n");
      out.write("        width: 0.1px;\r\n");
      out.write("        height: 11px;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("        margin: 0px 3px;\r\n");
      out.write("      }\r\n");
      out.write("      .topMenu {\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        flex-wrap: nowrap;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("      }\r\n");
      out.write("      .gnb {\r\n");
      out.write("        height: 57px;\r\n");
      out.write("      }\r\n");
      out.write("      .cata {\r\n");
      out.write("        border: 1px solid rgb(226, 226, 226);\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("        padding: 0px;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        flex-wrap: nowrap;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        height: 57px;\t\r\n");
      out.write("        font-size: 15px;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("      }\r\n");
      out.write("      .menuTitle {\r\n");
      out.write("        margin: 0px 30px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-family: \"Montserrat\", sans-serif;\r\n");
      out.write("      }\r\n");
      out.write("      .effCancle {\r\n");
      out.write("        margin-right: 0px;\r\n");
      out.write("      }\r\n");
      out.write("\t.bestContainer { \r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight:auto;\r\n");
      out.write("\tbackground-color: #fcfafa;\r\n");
      out.write("\t}\r\n");
      out.write("\t.mainWrap h1{\r\n");
      out.write("\tmargin: 50px 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.bestWrap { \r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\twidth: 1200px; \r\n");
      out.write("\theight: auto; \r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: row;\r\n");
      out.write("\tflex-wrap: no-wrap;\r\n");
      out.write("\tjustify-content: flex-start;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\t }\r\n");
      out.write("\t.bestItem { \r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("\t  }\r\n");
      out.write("\t.fntCenter{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.bestItem:nth-child(2){\r\n");
      out.write("\tmargin-left:10px;\r\n");
      out.write("\tmargin-right:10px;\r\n");
      out.write("\t}\r\n");
      out.write("      /* \r\n");
      out.write("         flex-direction으로 정렬방향을 지정하면 그 방향에 대한 축이 main축(axis)이된다. \r\n");
      out.write("         main축이 정해지면 자동으로 그에 수직으로 떨어지는 cross축이 그려진다.\r\n");
      out.write("         flex-wrap : 자식요소의 사이즈가 부모요소의 사이즈를 초과할 경우에 자식요소들을 감싸지 않고 무조건 한 줄에 요소들을 배치하겠다.\r\n");
      out.write("      \t  여러줄로 감싸는것이 아닌 한 줄로 감쌈\r\n");
      out.write("                  자식사이즈를 줄여서라도 한 줄로 만듦\r\n");
      out.write("         wrap : 여러줄로 감싸겠다 자식요소의 크기를 줄이지 않고  \r\n");
      out.write("         main axis를 기준으로 요소들을 정렬하고자 할땐 justify-content속성을 사용\r\n");
      out.write("         cross axis를 기준으로 요소들을 정렬하고자 할땐 align-content속성이나 align-item을 사용\r\n");
      out.write("\r\n");
      out.write("         요약\r\n");
      out.write("         1.나 플렉스박스 사용할거임\r\n");
      out.write("         2.정렬 방향 결정\r\n");
      out.write("         3.단 한줄로 모든 요소들을 배치할것인지 여러줄로 감싸 요소들을 배치할것인지 결정\r\n");
      out.write("         4.플렉스박스 타임\r\n");
      out.write("      */\r\n");
      out.write("      .subMenu {\r\n");
      out.write("        display: none;\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        flex-wrap: nowrap;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        background-color: #212121;\r\n");
      out.write("        opacity: 0.9;\r\n");
      out.write("        color: white;\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("      }\r\n");
      out.write("      .SuvMenu li {\r\n");
      out.write("      \tcursor:pointer;\r\n");
      out.write("      }\r\n");
      out.write("      .Title {\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        height: 110px;\r\n");
      out.write("        /* margin-right: 15px; */\r\n");
      out.write("        font-family: \"Montserrat\", sans-serif;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        line-height: 1.5;\r\n");
      out.write("      }\r\n");
      out.write("      .SuvMenu {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        padding-left: 0px;\r\n");
      out.write("      }\r\n");
      out.write("      .sec {\r\n");
      out.write("        margin: 0px 50px;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("      }\r\n");
      out.write("      .sec li {\r\n");
      out.write("        padding-left: 20px;\r\n");
      out.write("        padding-right: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      .frt li {\r\n");
      out.write("        padding-left: 20px;\r\n");
      out.write("      }\r\n");
      out.write("      .gnb {\r\n");
      out.write("        height: auto;\r\n");
      out.write("      }\r\n");
      out.write("      #pdtListTitle {\r\n");
      out.write("      \ttext-align: center;\r\n");
      out.write("      \tmargin-top: 110px;\r\n");
      out.write("      }\r\n");
      out.write("      .sort {\r\n");
      out.write("      \twidth: auto;\r\n");
      out.write("      \theight: auto;\r\n");
      out.write("      \tmargin: 0 auto;\r\n");
      out.write("      \tpadding-top: 15px;\r\n");
      out.write("      }\r\n");
      out.write("      .table {\r\n");
      out.write("      \tmargin: 0 auto;\r\n");
      out.write("      }\r\n");
      out.write("      select {\r\n");
      out.write("\t  -moz-appearance: none;\r\n");
      out.write("\t  -webkit-appearance: none;\r\n");
      out.write("\t  appearance: none;\r\n");
      out.write("\t  font-family: \"Noto Sansf KR\", sans-serif;\r\n");
      out.write("\t  font-size: 1rem;\r\n");
      out.write("\t  font-weight: 400;\r\n");
      out.write("\t  line-height: 1.5;\r\n");
      out.write("\t  color: #444;\r\n");
      out.write("\t  background-color: #fff;\r\n");
      out.write("\t  margin: 0;\r\n");
      out.write("\t  border: 1px solid #aaa;\r\n");
      out.write("\t  border-radius: 0.5em;\r\n");
      out.write("\t  box-shadow: 0 1px 0 1px rgba(0, 0, 0, 0.04);\r\n");
      out.write("\t}\r\n");
      out.write("\tinput[type=\"text\"] {\r\n");
      out.write("\t  -moz-appearance: none;\r\n");
      out.write("\t  -webkit-appearance: none;\r\n");
      out.write("\t  appearance: none;\r\n");
      out.write("\t  border: 1px solid #aaa;\r\n");
      out.write("\t  border-radius: 0.5em;\r\n");
      out.write("\t  box-shadow: 0 1px 0 1px rgba(0,0,0,0.04);\r\n");
      out.write("\t  color: #444;\r\n");
      out.write("\t  background-color: #fff;\r\n");
      out.write("\t  margin: 0;\r\n");
      out.write("\t  font-family: \"Noto Sansf KR\", sans-serif;\r\n");
      out.write("\t  font-size: 1rem;\r\n");
      out.write("\t  font-weight: 400;\r\n");
      out.write("\t  line-height: 1.5;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pr {\r\n");
      out.write("\t  width: 60px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.iptBtn {\r\n");
      out.write("\t  -moz-appearance: none;\r\n");
      out.write("\t  -webkit-appearance: none;\r\n");
      out.write("\t  appearance: none;\r\n");
      out.write("\t  border: none;\r\n");
      out.write("\t  border-radius: 0.5em;\r\n");
      out.write("\t  width: 90px;\r\n");
      out.write("\t  height:40px;\r\n");
      out.write("\t  font-size: 15px;\r\n");
      out.write("\t  font-weight: 700;\r\n");
      out.write("\t  background-color: #424141;\r\n");
      out.write("\t  color: #ffffff;\r\n");
      out.write("\t  margin-top: 17px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pdtTbl {\r\n");
      out.write("\t  margin: 0 auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t.blockTbl {\r\n");
      out.write("\t  margin: 0 auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pdtImg {\r\n");
      out.write("\t  padding-bottom: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.topTitle {\r\n");
      out.write("\t  background-color:#1D3932;\r\n");
      out.write("\t  text-align:center;\r\n");
      out.write("\t  border:1px solid black;\r\n");
      out.write("      padding:20px;\r\n");
      out.write("      color: #ffffff;\r\n");
      out.write("\t}\r\n");
      out.write("\t  .footer {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 300px;\r\n");
      out.write("      border:1px solid black;\r\n");
      out.write("      background-color: #1D3932;\r\n");
      out.write("      color: #ffffff;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      padding-top: 60px;\r\n");
      out.write("      }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<main>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("      <header class=\"header\">\r\n");
      out.write("        <div class=\"topMenu\">\r\n");
      out.write("          <div class=\"box left\">\r\n");

if (loginMember == null) {

      out.write("\r\n");
      out.write("            <a href=\"login_view.login\"><span>LOGIN</span></a>\r\n");
      out.write("            <div class=\"line\"><div class=\"lineItem\"></div></div>\r\n");
      out.write("            <a href=\"join_view.join\"><span>JOIN</span></a>\r\n");

} else {

      out.write('\r');
      out.write('\n');
      out.print(loginMember.getMlid() + "(" + loginMember.getMlname() + ")" );
      out.write(" <div class=\"line\"><div class=\"lineItem\"></div></div>\r\n");
      out.write("<a href=\"logout_proc.login\">LOGOUT</a>\r\n");

}

      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"box right\">\r\n");
      out.write("            <a href=\"#\"\r\n");
      out.write("              ><span><i class=\"fas fa-shopping-cart\"></i></span\r\n");
      out.write("            ></a>\r\n");
      out.write("            <div class=\"line\"><div class=\"lineItem\"></div></div>\r\n");
      out.write("            <a href=\"#\"\r\n");
      out.write("              ><span><i class=\"fas fa-search\"></i></span\r\n");
      out.write("            ></a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"logoBox\">\r\n");
      out.write("          <a href=\"index_view.main\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"images/포에트리 가든.png\"\r\n");
      out.write("              alt=\"메인로고\"\r\n");
      out.write("              width=\"406px\"\r\n");
      out.write("              height=\"73px\"\r\n");
      out.write("              id=\"logoImg\"\r\n");
      out.write("            />\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </header>\r\n");
      out.write("      <nav class=\"gnb\">\r\n");
      out.write("        <div class=\"list cata\">\r\n");
      out.write("          <div class=\"menuTitle\" onclick=\"location.href='pdt_list.pdt?loginMember=");
      out.print(loginMember);
      out.write("';\">SHOP</div>\r\n");
      out.write("          <div class=\"menuTitle\">POST</div>\r\n");
      out.write("          <div class=\"menuTitle\" id=\"effCancle\">CENTER</div>\r\n");
      out.write("        </div>\r\n");
      out.write("         <div class=\"slideShow\" id=\"slide\">\r\n");
      out.write("          <div class=\"subMenu\">\r\n");
      out.write("            <div class=\"frt Title\">\r\n");
      out.write("              <ul class=\"frt SuvMenu\">\r\n");
      out.write("                <li>PLANTS</li>\r\n");
      out.write("                <li>PLANT+POT</li>\r\n");
      out.write("                <li>POTS</li>\r\n");
      out.write("                <li>OTHER</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sec Title\">\r\n");
      out.write("              <ul class=\"secc SuvMenu\">\r\n");
      out.write("                <li>POST</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"thd Title\">\r\n");
      out.write("              <ul class=\"trd SuvMenu\">\r\n");
      out.write("                <li>NOTICE</li>\r\n");
      out.write("                <li>REVIEW</li>\r\n");
      out.write("                <li>Q&N</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("<h2 id=\"pdtListTitle\">SHOP</h2>\r\n");
      out.write("<div class=\"item sort\">\r\n");
      out.write("<form name=\"frmSch\" action=\"\" method=\"get\" >\r\n");
      out.write("<table width=\"800\" cellpadding=\"5\" class=\"table\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th width=\"15%\">가격대</th>\r\n");
      out.write("<td width=\"35%\">\r\n");
      out.write("\t<input type=\"text\" name=\"sprice\" class=\"pr\" value=\"");
      out.print(sprice);
      out.write("\"/>원 이상\r\n");
      out.write("\t<input type=\"text\" name=\"eprice\" class=\"pr\" value=\"");
      out.print(eprice);
      out.write("\"/>원 이하\r\n");
      out.write("</td>\r\n");
      out.write("<th width=\"15%\">상품명</th>\r\n");
      out.write("<td width=\"35%\"><input type=\"text\" name=\"keyword\" class=\"date\"/></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>정렬방식</th>\r\n");
      out.write("<td>\r\n");
      out.write("\t<select name=\"ord\">\r\n");
      out.write("\t\t<option value=\"\" ");
 if (ord.equals("")) { 
      out.write("selected=\"selected\"");
 } 
      out.write(">상품아이디(오름차순)</option>\r\n");
      out.write("\t\t<option value=\"namea\" ");
 if (ord.equals("namea")) { 
      out.write("selected=\"selected\"");
 } 
      out.write(">상품명(오름차순)</option>\r\n");
      out.write("\t\t<option value=\"pricea\" ");
 if (ord.equals("pricea")) { 
      out.write("selected=\"selected\"");
 } 
      out.write(">낮은 가격순(오름차순)</option>\r\n");
      out.write("\t\t<option value=\"priced\" ");
 if (ord.equals("priced")) { 
      out.write("selected=\"selected\"");
 } 
      out.write(">높은 가격순(내림차순)</option>\r\n");
      out.write("\t\t<option value=\"datea\" ");
 if (ord.equals("datea")) { 
      out.write("selected=\"selected\"");
 } 
      out.write(">오래된 등록일순(오름차순)</option>\r\n");
      out.write("\t\t<option value=\"dated\" ");
 if (ord.equals("dated")) { 
      out.write("selected=\"selected\"");
 } 
      out.write(">최근 등록일순(내림차순)</option>\r\n");
      out.write("\t\t<option value=\"salecntd\" ");
 if (ord.equals("salecntd")) { 
      out.write("selected=\"selected\"");
 } 
      out.write(">많이 팔린순(내림차순)</option>\r\n");
      out.write("\t\t<option value=\"reviewd\" ");
 if (ord.equals("reviewd")) { 
      out.write("selected=\"selected\"");
 } 
      out.write(">리뷰 개수순(내림차순)</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("</td>\r\n");
      out.write("<th>페이지 크기</th>\r\n");
      out.write("<td>\r\n");
      out.write("\t<select name=\"psize\">\r\n");
      out.write("\t\t<option value=\"12\" ");
 if (psize == 12) { 
      out.write("selected=\"selected\"");
 } 
      out.write(">12 개</option>\r\n");
      out.write("\t\t<option value=\"6\" ");
 if (psize == 6) { 
      out.write("selected=\"selected\"");
 } 
      out.write(">6 개</option>\r\n");
      out.write("\t\t<option value=\"8\" ");
 if (psize == 8) { 
      out.write("selected=\"selected\"");
 } 
      out.write(">8 개</option>\r\n");
      out.write("\t\t<option value=\"24\" ");
 if (psize == 24) { 
      out.write("selected=\"selected\"");
 } 
      out.write(">24 개</option>\r\n");
      out.write("\t</select> 씩 보여주기\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t<input type=\"submit\" value=\"상품 검색\" class=\"iptBtn\" />\r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t<input type=\"reset\" value=\"다시 입력\" class=\"iptBtn\"/>\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("<h1 class=\"topTitle\">HOYAS</h1>\r\n");
      out.write("<table width=\"800\" cellpadding=\"5\" class=\"pdtTbl\">\r\n");

int max = 3;	// 한 행에서 보여줄 상품의 최대 개수
if (psize == 8)	max = 4;

if (pdtList != null && rcnt > 0) {	// 검색결과가 있으면
	String lnk = "", price = "", soldout = "";
	for (int i = 0 ; i < pdtList.size() && i < psize ; i++) {
		lnk = "<a href='pdt_view.pdt?id=" + pdtList.get(i).getPl_id() + args + "'>";
		if (i % max == 0)	out.println("<tr align=\"center\">");
		price = pdtList.get(i).getPl_price() + "";
		if (pdtList.get(i).getPl_discount() > 0) {	// 할인율이 있으면
			float rate = (float)pdtList.get(i).getPl_discount() / 100;
			int dcPrice = Math.round(pdtList.get(i).getPl_price() - (pdtList.get(i).getPl_price() * rate));
			price = "<del>" + price + "</del><br />할인가 : " + dcPrice;
		}
		soldout = "";
		if (pdtList.get(i).getPl_stock() == 0)
			soldout = " <img src='/hoyaMall/images/soldout.png' width='50' align='absmiddle' />";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<td class=\"itemList\">\r\n");
      out.write("\t<div class=\"pdtBox");
      out.print(max);
      out.write("\">\t\t\r\n");
      out.write("\t\t");
      out.print(lnk );
      out.write("<img src=\"/hoyaMall/product/pdt_img/");
      out.print(pdtList.get(i).getPl_img1() );
      out.write("\" width=\"");
      out.print(max == 3 ? 265 : 190 );
      out.write("\" height=\"");
      out.print(max == 3 ? 230 : 140 );
      out.write("\" class=\"pdtImg\"/></a><br />\r\n");
      out.write("\t\t");
      out.print(lnk + pdtList.get(i).getPl_name());
      out.write("</a>");
      out.print(soldout );
      out.write("<br />판매가 : ");
      out.print(price );
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</td>\r\n");
      out.write("\t\r\n");

		if (i % max == max - 1)	out.println("</tr>");
	}
} else {
	out.println("<tr><td align='center'>검색결과가 없습니다.</td></tr>");
}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br />\r\n");
      out.write("<table width=\"800\" cellpadding=\"5\" class=\"blockTbl\">\r\n");
      out.write("<tr><td align=\"center\">\r\n");

if (rcnt > 0) {	// 검색결과 상품들이 있을 경우에만 페이징을 함
	if (cpage == 1) {
		out.println("[<<]&nbsp;&nbsp;[<]&nbsp;&nbsp;");
	} else {
		out.print("<a href='pdt_list.pdta?cpage=1" + schArgs + "'>");
		out.println("[<<]</a>&nbsp;&nbsp;");
		out.print("<a href='pdt_list.pdta?cpage=" + (cpage - 1) + schArgs + "'>");
		out.println("[<]</a>&nbsp;&nbsp;");
	}

	for (int i = 1, j = spage ; i <= bsize && j <= pcnt ; i++, j++) {
		if (cpage == j) {
			out.println("&nbsp;<strong>" + j + "</strong>&nbsp;");
		} else {
			out.print("&nbsp;<a href='pdt_list.pdta?cpage=" + j + schArgs + "'>");
			out.println(j + "</a>&nbsp;");
		}
	}

	if (cpage == pcnt) {
		out.println("&nbsp;&nbsp;[>]&nbsp;&nbsp;[>>]");
	} else {
		out.print("&nbsp;&nbsp;<a href='pdt_list.pdta?cpage=" + (cpage + 1) + schArgs + "'>");
		out.println("[>]</a>");
		out.print("&nbsp;&nbsp;<a href='pdt_list.pdta?cpage=" + pcnt + schArgs + "'>");
		out.println("[>>]</a>");
	}
}

      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</main>\r\n");
      out.write("<h1 class=\"topTitle\">POTS</h1>\r\n");
      out.write("<article class=\"bestContainer\">\r\n");
      out.write(" <section class=\"bestWrap\">\r\n");
      out.write(" ");
 for(int i = 0 ; i < pdtPotList.size() ; i++) { 
      out.write("\r\n");
      out.write("  <div class=\"bestItem\">\r\n");
      out.write("  <div class=\"image\">\r\n");
      out.write(" \t<img src=\"/hoyaMall/product/pdt_img/");
      out.print(pdtPotList.get(i).getPl_img1() );
      out.write("\" width=\"400px\" height=\"400px\"/>\r\n");
      out.write(" \t");
 System.out.println(pdtPotList.get(i).getPl_img1()); 
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("  \t<div class=\"fntCenter\">");
      out.print(pdtPotList.get(i).getPl_name() );
      out.write("</div>\r\n");
      out.write("  \t<div class=\"fntCenter\">");
      out.print(pdtPotList.get(i).getPl_price() );
      out.write("</div>\r\n");
      out.write("  </div>\r\n");
      out.write(" ");
 } 
      out.write("\r\n");
      out.write(" </section>\r\n");
      out.write("</article>\r\n");
      out.write(" <script src=\"js/jquery-3.5.1.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("      //마우스커서가 해당 요소위에 올라가면 동작이 되는 코드\r\n");
      out.write("      //제이쿼리 문법을 쓰기위해 현재 이벤트를 먹인 문서를 브라우저가 다운로드 받아 준비된 상태로 만든다\r\n");
      out.write("      //처음에 메뉴가 숨겨진상태여야함\r\n");
      out.write("      //마우스 포인터가 해당 요소에 오버가 되면 동작이됨\r\n");
      out.write("      //포인터가 열린 서브메뉴판에서 벗어나면 다시 메뉴가 들어감\r\n");
      out.write("      //문제점: 메뉴에 오버했을때 나오는거는 ok 그런데 그 요소에 대해서만 이벤트가 적용이된상태임\r\n");
      out.write("      $(document).ready(function () {\r\n");
      out.write("        $(\".menuTitle\").mouseover(function () {\r\n");
      out.write("          $(\".subMenu\").css(\"display\", \"flex\").stop().slideDown();\r\n");
      out.write("        });\r\n");
      out.write("        $(\".subMenu\").mouseleave(function () {\r\n");
      out.write("          $(this).css(\"display\", \"none\").stop().slideUp();\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("     <footer>\r\n");
      out.write("     \t<div class=\"footer\">\r\n");
      out.write("     \t\t<p>\r\n");
      out.write("     \t\t<strong>Poetry garden(포에트리 가든)</strong>\r\n");
      out.write("     \t\t<br>\r\n");
      out.write("     \t\tCompany: 포에트리가든 | 대표자: 홍길동\r\n");
      out.write("     \t\t<br>\r\n");
      out.write("     \t\tAddr: 서울시 마포구  26길 18-4(픽업 예약방문)\r\n");
      out.write("     \t\t</p>\r\n");
      out.write("     \t\t<p>\r\n");
      out.write("     \t\tE-mail: gksdidwnd91@naver.com\r\n");
      out.write("     \t\t<br>\r\n");
      out.write("     \t\tCS: 010-3322-5232 (AM.10 ~ PM.6 주말 및 공휴일 휴무)\r\n");
      out.write("     \t\t</p>\r\n");
      out.write("     \t\t이용약관ㆍ개인정보처리방침\r\n");
      out.write("     \t</div>\r\n");
      out.write("     </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
